/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SimpleMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7813954705042861333L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SimpleMessage\",\"namespace\":\"org.example.avro\",\"fields\":[{\"name\":\"content\",\"type\":\"string\",\"doc\":\"Message content\"},{\"name\":\"date_time\",\"type\":\"string\",\"doc\":\"Datetime when the message was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SimpleMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SimpleMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SimpleMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SimpleMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SimpleMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SimpleMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SimpleMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SimpleMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SimpleMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Message content */
  private java.lang.CharSequence content;
  /** Datetime when the message was generated */
  private java.lang.CharSequence date_time;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SimpleMessage() {}

  /**
   * All-args constructor.
   * @param content Message content
   * @param date_time Datetime when the message was generated
   */
  public SimpleMessage(java.lang.CharSequence content, java.lang.CharSequence date_time) {
    this.content = content;
    this.date_time = date_time;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return content;
    case 1: return date_time;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: content = (java.lang.CharSequence)value$; break;
    case 1: date_time = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'content' field.
   * @return Message content
   */
  public java.lang.CharSequence getContent() {
    return content;
  }


  /**
   * Sets the value of the 'content' field.
   * Message content
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'date_time' field.
   * @return Datetime when the message was generated
   */
  public java.lang.CharSequence getDateTime() {
    return date_time;
  }


  /**
   * Sets the value of the 'date_time' field.
   * Datetime when the message was generated
   * @param value the value to set.
   */
  public void setDateTime(java.lang.CharSequence value) {
    this.date_time = value;
  }

  /**
   * Creates a new SimpleMessage RecordBuilder.
   * @return A new SimpleMessage RecordBuilder
   */
  public static org.example.avro.SimpleMessage.Builder newBuilder() {
    return new org.example.avro.SimpleMessage.Builder();
  }

  /**
   * Creates a new SimpleMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SimpleMessage RecordBuilder
   */
  public static org.example.avro.SimpleMessage.Builder newBuilder(org.example.avro.SimpleMessage.Builder other) {
    if (other == null) {
      return new org.example.avro.SimpleMessage.Builder();
    } else {
      return new org.example.avro.SimpleMessage.Builder(other);
    }
  }

  /**
   * Creates a new SimpleMessage RecordBuilder by copying an existing SimpleMessage instance.
   * @param other The existing instance to copy.
   * @return A new SimpleMessage RecordBuilder
   */
  public static org.example.avro.SimpleMessage.Builder newBuilder(org.example.avro.SimpleMessage other) {
    if (other == null) {
      return new org.example.avro.SimpleMessage.Builder();
    } else {
      return new org.example.avro.SimpleMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for SimpleMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SimpleMessage>
    implements org.apache.avro.data.RecordBuilder<SimpleMessage> {

    /** Message content */
    private java.lang.CharSequence content;
    /** Datetime when the message was generated */
    private java.lang.CharSequence date_time;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.avro.SimpleMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.date_time)) {
        this.date_time = data().deepCopy(fields()[1].schema(), other.date_time);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SimpleMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.avro.SimpleMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.content)) {
        this.content = data().deepCopy(fields()[0].schema(), other.content);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date_time)) {
        this.date_time = data().deepCopy(fields()[1].schema(), other.date_time);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'content' field.
      * Message content
      * @return The value.
      */
    public java.lang.CharSequence getContent() {
      return content;
    }


    /**
      * Sets the value of the 'content' field.
      * Message content
      * @param value The value of 'content'.
      * @return This builder.
      */
    public org.example.avro.SimpleMessage.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.content = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * Message content
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'content' field.
      * Message content
      * @return This builder.
      */
    public org.example.avro.SimpleMessage.Builder clearContent() {
      content = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date_time' field.
      * Datetime when the message was generated
      * @return The value.
      */
    public java.lang.CharSequence getDateTime() {
      return date_time;
    }


    /**
      * Sets the value of the 'date_time' field.
      * Datetime when the message was generated
      * @param value The value of 'date_time'.
      * @return This builder.
      */
    public org.example.avro.SimpleMessage.Builder setDateTime(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.date_time = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date_time' field has been set.
      * Datetime when the message was generated
      * @return True if the 'date_time' field has been set, false otherwise.
      */
    public boolean hasDateTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date_time' field.
      * Datetime when the message was generated
      * @return This builder.
      */
    public org.example.avro.SimpleMessage.Builder clearDateTime() {
      date_time = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SimpleMessage build() {
      try {
        SimpleMessage record = new SimpleMessage();
        record.content = fieldSetFlags()[0] ? this.content : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date_time = fieldSetFlags()[1] ? this.date_time : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SimpleMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<SimpleMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SimpleMessage>
    READER$ = (org.apache.avro.io.DatumReader<SimpleMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.content);

    out.writeString(this.date_time);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);

      this.date_time = in.readString(this.date_time instanceof Utf8 ? (Utf8)this.date_time : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.content = in.readString(this.content instanceof Utf8 ? (Utf8)this.content : null);
          break;

        case 1:
          this.date_time = in.readString(this.date_time instanceof Utf8 ? (Utf8)this.date_time : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










